name: 'greentaxi'
version: '1.0.0'
config-version: 2

profile: 'greentaxi'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  greentaxi:
    marts:
      +materialized: table
