apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greentaxi-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/yvan-ai/GreenTaxi-GitOps-Pipeline"
    targetRevision: HEAD
    path: k8s/monitoring
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
