apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: greentaxi-dev

resources:
  - ../../base

patches:
  # Dev runs hourly to catch model regressions quickly
  - target:
      kind: CronJob
      name: greentaxi-dbt-run
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "0 * * * *"
