apiVersion: batch/v1
kind: CronJob
metadata:
  name: greentaxi-dbt-run
spec:
  schedule: "0 0 * * *" # Every night at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dbt
            image: ghcr.io/yvan-ai/greentaxi-dbt:f09b783fe30b7cbad3c9b557563244e8aef624c6
            imagePullPolicy: Always
            env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: database
          restartPolicy: OnFailure
